function string = cell_identifier_to_string( ...
    cell_identifier, ...
    maximum_cell_identifier)
string = sprintf([ ...
    '%0', ...
    num2str(ceil(log10(maximum_cell_identifier + 1))), ...
    'd'], cell_identifier);
end
