function [ ...
    charge_discharged_from_cell, ...
    voltage_source_voltage, ...
    mean_internal_conductance] = ...
    read_cell_discharge_curve(fid)
number_of_points = fread(fid, 1, 'uint64');
discharge_curve = ...
    reshape( ...
    fread(fid, 2 * number_of_points, 'double'), ...
    2, ...
    number_of_points);
mean_internal_conductance = fread(fid, 1, 'double');
charge_discharged_from_cell = discharge_curve(1, :)';
voltage_source_voltage = discharge_curve(2, :)';
end
