function write_cell_discharge_curve( ...
    fid, ...
    charge_supplied, ...
    open_circuit_voltage, ...
    mean_internal_conductance, ...
    work)
fwrite(fid, numel(charge_supplied), 'uint64');
fwrite(fid, [charge_supplied'; open_circuit_voltage'; work'], 'double');
fwrite(fid, mean_internal_conductance, 'double');
end
