function write_cell(fid, the_cell)
fwrite(fid, numel(the_cell.charge_supplied), 'uint64');
fwrite( ...
    fid, ...
    [ ...
        the_cell.charge_supplied'; ...
        the_cell.open_circuit_voltage'; ...
        the_cell.work'], ...
    'double');
fwrite(fid, the_cell.mean_internal_conductance, 'double');
end
