function the_logical = cell_eq(lhs, rhs)
the_logical = ...
    all([ ...
        lhs.charge_supplied == rhs.charge_supplied; ...
        lhs.open_circuit_voltage == rhs.open_circuit_voltage; ...
        lhs.mean_internal_conductance == ...
            rhs.mean_internal_conductance; ...
        lhs.work == rhs.work]);
end
