function the_cell = ...
    make_cell( ...
        charge_supplied, ...
        open_circuit_voltage, ...
        mean_internal_conductance, ...
        work)
    the_cell = struct( ...
        'charge_supplied', charge_supplied, ...
        'open_circuit_voltage', open_circuit_voltage, ...
        'mean_internal_conductance', mean_internal_conductance, ...
        'work', work);
end
